name: CI/CD
on:
  push:
    branches: ['main']
    # paths:
    #   ['src/stories/**', 'src/components/**', 'src/styles/**', '.storybook/**']
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.4'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: deps-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Eslint
        run: npm run lint.strict
      - name: Build
        run: npm run build
      - name: Unit tests
        run: npm run test.unit       
      - name: Browser tests
        run: npm run test.browser
  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout 🛎️
  #       uses: actions/checkout@v2.3.1
  #       with:
  #         persist-credentials: false
  #     - name: Install and Build 🔧
  #       run: |
  #         npm ci
  #         npm run storybook.build
  #     - name: Deploy 🚀
  #       uses: JamesIves/github-pages-deploy-action@4.1.5
  #       with:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         BRANCH: main
  #         FOLDER: storybook-static
  #         CLEAN: true
  #         TARGET_FOLDER: docs
