name: PR
on:
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap
      - run: npm run lint.strict
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CYPRESS_CACHE_FOLDER: cypress/cache
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap
      - uses: actions/cache@v2
        id: cache-cypress
        with:
          path: cypress/cache
          key: cypress-cache-${{ hashFiles('package-lock.json') }}
      - name: Unit tests
        run: npm run test.unit
      - name: Browser tests
        run: npm run test.browser
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap
      - run: npm run build
