name: Release
on:
  push:
    branches: ['main']
    paths-ignore: ['src/stories/**', '.storybook/**']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap
      - run: npm run lint.strict
  preBuild:
    name: preBuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap
      - run: npm run build.code
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CYPRESS_CACHE_FOLDER: cypress/cache
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap
      - uses: actions/cache@v2
        id: cache-cypress
        with:
          path: cypress/cache
          key: cypress-cache-${{ hashFiles('package-lock.json') }}
      - name: Unit tests
        run: npm run test.unit
      - name: Browser tests
        run: npm run test.browser
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [lint, test, preBuild]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
