name: Storybook
on:
  push:
    branches: ['main']
    paths:
      ['src/stories/**', 'src/components/**', 'src/styles/**', '.storybook/**']

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap
      - name: Build
        run: npm run storybook.build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: storybook-static
          clean: true
